cookie:
  expiry_days: 30
  key: your_secret_key
  name: study_buddy_cookie
credentials:
  usernames:
    rebornify:
      email: oyscaleb@gmail.com
      failed_login_attempts: 0
      first_name: Caleb
      last_name: Ong
      logged_in: true
      password: $2b$12$iydxrwkj/aBjGCpy53GdqOIrOwxsJJeXOFEsuyJLHo2FIOavZeR.i
      password_hint: Default
      roles: null
